version: '3'

services:

  pm1:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM1}
    container_name: ${PM1}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    depends_on:
      - "pm3"
    links:
      - "pm2"
      - "pm3"
    ports:
      - 3307:3306

  pm2:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM2}
    container_name: ${PM2}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    depends_on:
      - "pm3"
    links:
      - "pm3"
    ports:
      - 3308:3306

  pm3:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM3}
    container_name: ${PM3}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    ports:
      - 3309:3306

  mx1:
    image: ${MX_IMAGE_NAME}
    hostname: ${MX1}
    container_name: ${MX1}
    volumes:
      - maxscale1:/var/lib/maxscale
      - ${PWD}/etc/maxscale.cnf:/etc/maxscale.cnf
    depends_on:
      - "pm1"
    env_file:
      - .env
    links:
      - "pm1"
      - "pm2"
      - "pm3"
    ports:
      - 3310:3306
      - 8989:8989

  mx2:
    image: ${MX_IMAGE_NAME}
    hostname: ${MX2}
    container_name: ${MX2}
    volumes:
      - maxscale2:/var/lib/maxscale
      - ${PWD}/etc/maxscale.cnf:/etc/maxscale.cnf
    depends_on:
      - "pm1"
    env_file:
      - .env
    links:
      - "mx1"
      - "pm1"
      - "pm2"
      - "pm3"
    ports:
      - 3311:3306
      - 8990:8989

volumes:
  data1:
  data2:
  data3:
  maxscale1:
  maxscale2:
  storagemanager:
