version: '3'

services:

  pm1:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM1}
    container_name: ${PM1}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    depends_on:
      - "pm3"
    links:
      - "pm2"
      - "pm3"
    ports:
      - 3307:3306

  pm2:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM2}
    container_name: ${PM2}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    depends_on:
      - "pm3"
    links:
      - "pm3"
    ports:
      - 3308:3306

  pm3:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM3}
    container_name: ${PM3}
    volumes:
      - data1:/var/lib/columnstore/data1
      - data2:/var/lib/columnstore/data2
      - data3:/var/lib/columnstore/data3
      - storagemanager:/var/lib/columnstore/storagemanager
    env_file:
      - .env
    ports:
      - 3309:3306

volumes:
  data1:
  data2:
  data3:
  storagemanager:
